# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170220_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='ref_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('story', 'Story'), ('bug', 'Bug'), ('improvement', 'Improvement'), ('sub-task', 'Sub Task')], default='improvement', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todo.Project'),
            preserve_default=False,
        ),
    ]
