# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170327_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='task',
            new_name='tasks',
        ),
    ]
