# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170227_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimation',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='forecast',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
