# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170309_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
