# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20170328_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_sprint', to='todo.Sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='task',
            field=models.ManyToManyField(blank=True, null=True, related_name='sprint_task', to='todo.Task'),
        ),
    ]
