# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20170328_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Sprint'),
        ),
    ]
