# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_comments', to='todo.Comment'),
        ),
    ]
